# frozen_string_literal: true

source "https://rubygems.org"


gem "bundler", "2.4.12"
gem "allure-cucumber", "2.20"
gem "cucumber", "8.0.0"
gem "capybara", "3.39.0"
gem "selenium-webdriver", "4.9.0"
gem "rspec", "3.12.0"
gem "faker", "3.2"
gem "mongo", "2.18.0"

# gem "rails"
